Repository CoconutMacaroon/D-D-Stuff, pull requests merged in 2020-11, with the labels that each got.

#9 Races section
  dnd-5e/Races.md
Labels: additions, races

#16 Minor formatting changes
  dnd-5e/Races.md
Labels: races

#17 Create README.md
  dnd-5e/README.md
Labels: additions, meta, races

#18 Update readme for style guide
  README.md
Labels: meta

#21 Add in the Ash wastes lore
  dnd-5e/campaign fluff.md
Labels: additions, lore
